In [ ]:
# 첨가행렬
A = matrix([[1,1,2], [2,4,-3], [3,6,-5]])
b = vector([9,1,0])
print(A.augment(b))
# [ 1  1  2  9]
# [ 2  4 -3  1]
# [ 3  6 -5  0]

In [ ]:
#기약행사다리꼴
A = matrix([[1, 1, 1, 4, 4],
			[2, 3, 4, 9, 16],
			[-2, 0, 3, -7, 11]])

print("RREF(A) =")
print(A.rref())

# RREF(A) =
# [ 1  0  0  2 -1]
# [ 0  1  0  3  2]
# [ 0  0  1 -1  3]

In [ ]:
# 기약행사다리꼴
A = matrix([[1, -2, 1],
			[2, -2, 1],
			[3, 1, -5],
            [0, -1, 2],
            [-6, 0, 7]])

b = vector([7, 5, 0, -4, -10])
A.augment(b).rref()
# [1 0 0 0]
# [0 1 0 0]
# [0 0 1 0]
# [0 0 0 1]
# [0 0 0 0]
A.solve_right(b)
#ValueError: matrix equation has no solutions

In [ ]:
A = matrix([[1, -2, 3], [4, 5, 0]])
B = matrix([[1, 2, -4], [3, -1, 2],[0, 5, 3]])
C = matrix([[5, 4], [-3, 2], [2, 1]])
D = matrix([[3, 0, 1]])
print("A^T =")
print(A.transpose())   # 행렬의 전치행렬 A.transpose() 구하기
print()
print("B^T =")
print(B.transpose())

# A^T =
# [ 1  4]
# [-2  5]
# [ 3  0]

# B^T =
# [ 1  3  0]
# [ 2 -1  5]
# [-4  2  3]

In [ ]:
A = random_matrix(ZZ, 7, 12)  # 임의의 7x12 정수(ZZ) 행렬 A를 생성!
print("A =")
print(A)
print()
print("A^T =")
print(A.transpose())  # 생성한 행렬 A의 전치행렬 A.transpose() 구하기

In [1]:
import numpy as np
A = np.random.randint(5, size=(5, 7))  # 임의의 (0~4 사이의 수만으로 이루어진) 5x7 자연수 행렬 A를 생성!
print("A =")
print(A)
print()
print("A^T =")
print(A.transpose()) # 생성한 행렬 A의 전치행렬 A.transpose() 구하기

A =
[[2 1 1 3 3 1 1]
 [0 1 2 4 1 0 2]
 [4 4 2 0 0 2 4]
 [0 4 0 0 4 2 3]
 [0 3 4 3 4 1 3]]

A^T =
[[2 0 4 0 0]
 [1 1 4 4 3]
 [1 2 2 0 4]
 [3 4 0 0 3]
 [3 1 0 4 4]
 [1 0 2 2 1]
 [1 2 4 3 3]]
